[package]
name = "mkdev"
version = "3.1.0"
edition = "2021"

[[bin]]
name = "mk"
path = "src/main.rs"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
hyperpolyglot = "0.1.7"
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
whoami = "1.5.2"
