[package]
name = "mkdev"
version = "3.1.2"
edition = "2021"
authors = ["James Craven <4jamesccraven@gmail.com>"]
description = "Save your boilerplate instead of writing it."

[[bin]]
name = "mk"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["cargo", "derive"] }
dirs = "5.0.1"
hyperpolyglot = "0.1.7"
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
