[package]
name = "mkdev-recipe"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "5.0.1"
hyperpolyglot = "0.1.7"
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
