language: py
extension: .py
templates:
  default:
    filename: default.py
    rename: true
    data: "# IMPORTS\n\ndef main() -> None:\n    ...\n\n\nif __name__ == '__main__':\n\
      \    main()\n"
  init:
    filename: __init__.py
    rename: false
    data: '# IMPORTS


      __all__ = []

      '
recipes:
  default:
  - tmp default
  module:
  - tmp init
