language: tex
extension: .tex
templates:
  default:
    filename: default.tex
    rename: true
    data: '\documentclass[12pt]{article}

      \usepackage{amsmath,amssymb,amsfonts}

      \usepackage[margin=1in]{geometry}

      \usepackage{graphicx}

      \title{}

      \author{}



      \begin{document}

      \fontsize{14}{22}\selectfont

      \maketitle



      \end{document}'
  beamer:
    filename: beamer.tex
    rename: true
    data: '% Imports

      \documentclass[9pt, dvipsnames]{beamer}

      \usepackage{times}

      \usepackage{amsmath}

      \usepackage{amsthm}

      \usepackage{verbatim}

      \usepackage{anyfontsize}

      \usepackage{subcaption}

      \usepackage{graphicx}

      \usepackage[export]{adjustbox}

      \usepackage[multidot]{grffile}

      \usepackage{tabularx}

      \usepackage{tikz}

      \usepackage{wasysym}

      \usepackage{amsmath,amssymb,amsfonts}

      % \usepackage[margin=1in]{geometry}


      % Beamer Themes

      \usetheme[secheader]{Boadilla}

      \usecolortheme{beaver}

      \usefonttheme{professionalfonts}

      \setbeamertemplate{caption}[numbered]


      % Counter

      \newcounter{saveenumi}

      \resetcounteronoverlays{saveenumi}


      % Preamble

      \title{}

      \author{}

      \date{}



      \begin{document}



      \maketitle



      \end{document}'
recipes:
  default:
  - tmp default
  beamer:
  - tmp beamer
