name: Build Binaries

on:
  push:
    tags:
      - 'v*' # Triggers only on version tags like v3.1.2

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary with LICENSE
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/mk dist/mk
          cp LICENSE dist/LICENSE

          cd dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv mk mk.exe
            7z a mk-${{ matrix.target }}.zip mk.exe LICENSE
          else
            tar -czf mk-${{ matrix.target }}.tar.gz mk LICENSE
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
